modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPL-3.0"
issueTrackerURL = "https://github.com/Team-Fruit/SignPicture/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/Team-Fruit/SignPicture"
logoFile = "assets/signpic/icon.png"
authors = "TeamFruit, Kamesuta"
description = '''Display images on signs in Minecraft'''

[[dependencies.signpic]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.signpic]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "CLIENT"
